services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      nousnews:
        ipv4_address: 172.30.50.11

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - nousnews_db:/var/lib/postgresql/data
    networks:
      nousnews:
        ipv4_address: 172.30.50.10

volumes:
  nousnews_db:

networks:
  nousnews:
    ipam:
      config:
        - subnet: 172.30.50.0/24
