version: "3.9"

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8210:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      nousnews:
        aliases:
          - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
      - nousnews_db:/var/lib/postgresql/data
    networks:
      - nousnews

volumes:
  nousnews_db:

networks:
  nousnews:
    external: true
